### ISSUE TITLE
Need Arbitrum tokenlist

### ISSUE THREAD

**Issue by 0xModene** [IndexCoop/tokenlists#10]
Required:
- [ ] `arbitrum.ts` created and lists exported
- [ ] arbitrum tokenlist follows patterns
- [ ] should include empty Index Coop tokenlist, appended to main list, just like the other lists in `src/lists`
- [ ] exported appropriately in `src/index.ts`
- [ ] should roughly mirror the tokenlist [here](https://bridge.arbitrum.io/token-list-42161.json)

**Comment by tytarman** [comment]
Guess I'll do this too while I'm already adding some others
