### ISSUE TITLE
Add Index token constants by chain

### ISSUE THREAD

**Issue by 0xonramp** [IndexCoop/tokenlists#58]
IndexEthereum.ETH2X
IndexEthereum.HYETH

IndexArbitrum.ETH2X

etc

**Comment by janndriessen** [comment]
Suggestions for research:
* outline current use cases e.g. do we need always by symbol or sometimes by address
* show how the future struct what improve the use cases
* research solutions from other forked Uniswap [tokenlists](https://tokenlists.org/) which this project is based on. I can imagine there must be ideas around how to best implement this already - or possibly existing tools (if we want to continue using this format of tokenlists)?

**Comment by janndriessen** [comment]
This PR https://github.com/IndexCoop/tokenlists/pull/59 might be interesting in this discussion.
