### ISSUE TITLE
Need Optimism tokenlist

### ISSUE THREAD

**Issue by 0xModene** [IndexCoop/tokenlists#9]
Required:
- [ ] `optimism.ts` created and lists exported
- [ ] optimism tokenlist follows patterns
- [ ] should include empty Index Coop tokenlist, appended to main list, just like the other lists in `src/lists`
- [ ] exported appropriately in `src/index.ts`
- [ ] should roughly mirror all `chainId: 10` tokens [here](https://static.optimism.io/optimism.tokenlist.json)

**Comment by tytarman** [comment]
i gotchu boo
